# Generated by Django 5.0.1 on 2024-01-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_item', '0003_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя товара'),
        ),
    ]
