# Generated by Django 5.0.1 on 2024-01-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_item', '0004_alter_item_description_alter_item_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': ('Товар',), 'verbose_name_plural': ('Список товаров',)},
        ),
    ]
