version: '3.9'
services:
  db_app:
    image: postgres:15
    container_name: db_app
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_USER: ${db_user}
    ports:
      - "5431:5432"